name: Build and Publish Image

on:
  push:
    branches: [ "main" ]
    paths:
        - dockerfile-kasm-debian-bookworm-desktop
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  debian-image-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker image build -f dockerfile-kasm-debian-bookworm-desktop -t ghcr.io/bartekj/kasm-images/kasm-debian-bookworm-desktop:latest .

    - name: Push to GHCR
      run: |
        echo -n ${{ env.REGISTRY_PASSWORD }} | docker login ghcr.io -u ${{ env.REGISTRY_USER }} --password-stdin
        docker image push "ghcr.io/bartekj/kasm-images/kasm-debian-bookworm-desktop:latest"
    
